name: where_is_it
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.1
  drift: ^2.29.0
  path: ^1.9.1
  riverpod_annotation: ^3.0.3
  sqlite3_flutter_libs: ^0.5.41
  freezed_annotation: ^3.1.0
  uuid: ^4.5.2
  timezone: ^0.10.1
  shared_preferences: ^2.5.4
  flutter_animate: ^4.5.2
  google_fonts: ^6.3.3
  flutter_svg: ^2.2.3
  gap: ^3.0.1
  dotted_border: ^3.1.0
  cached_network_image: ^3.4.1
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  flutter_local_notifications: ^19.5.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  drift_dev: ^2.29.0
  riverpod_generator: ^3.0.3
  freezed: ^3.2.3
  json_serializable: ^6.11.2

flutter:
  uses-material-design: true
